// examples/react-site/demos/app/alert/custom-class.jsx
import { Alert as TinyAlert } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

const scopeId = 'scope-' + Math.random().toString(36).substr(2, 9);

function App(props) {
  return (
    <div>
      <style>
        {`[data-v="${scopeId}"] .customClass {
          background-color: pink;
        }`}
      </style>
      <div data-v={scopeId}>{props.children}</div>
    </div>
  );
}

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(
      <App>
        <TinyAlert customClass="customClass" type="error" description="type 为 error"></TinyAlert>
      </App>
    );
  }
}

export default CustomElement;

// examples/sites/demos/pc/app/alert/custom-class.vue
<template>
  <div>
    <tiny-alert custom-class="customClass" type="error" description="type 为 error"></tiny-alert>
  </div>
</template>

<script>
import { TinyAlert } from '@opentiny/vue'

export default {
  components: {
    TinyAlert
  }
}
</script>

<style scoped>
.customClass {
  background-color: pink;
}
</style>
