// examples/react-docs/demos/pc/app/alert/title.jsx
import { Alert as TinyAlert } from '@opentiny/react'

function App() {
  return (
    <div>
      <TinyAlert size="large" title="通过属性设置自定义 title"></TinyAlert>
      <br />
      <TinyAlert
        size="large"
        slots={{
          title: () => '通过 slot 设置自定义 title'
        }}></TinyAlert>
    </div>
  )
}

export default App

// examples/sites/demos/pc/app/alert/title.vue
<template>
  <div>
    <tiny-alert size="large" title="通过属性设置自定义 title"></tiny-alert>
    <br />
    <tiny-alert size="large">
      <template #title>通过 slot 设置自定义 title</template>
    </tiny-alert>
    <br />
    <tiny-alert size="large"></tiny-alert>
    <br />
    <tiny-alert size="large" type="success"></tiny-alert>
    <br />
    <tiny-alert size="large" type="error"></tiny-alert>
    <br />
    <tiny-alert size="large" type="warning"></tiny-alert>
  </div>
</template>

<script>
import { Alert } from '@opentiny/vue'

export default {
  components: {
    TinyAlert: Alert
  }
}
</script>
