// packages/react-components/date-range/src/mobile-first.jsx

    import { renderless, api } from '@opentiny/vue-renderless/date-range/vue'
    import '@opentiny/vue-theme/date-range/index.less'
    import { vc, If, Component, Slot, useSetup, useVm, $props, m } from '@opentiny/react-common'
    import {useRef} from 'react'
    export default function dateRange(props) {
      const {emitter,step,showWeekNumber,formatWeeks} = props
      const defaultProps = {
        ...$props,
        ...props,
        emitter,step,showWeekNumber,formatWeeks
      }
      const { ref, current: vm, parent } = useVm()
      const refDateRange=useRef()
const shortcut=useRef()
const minInput=useRef()
const minTimePicker=useRef()
const maxTimePicker=useRef()
      const { state,handleShortcutClick,handleMinTimePick,handleMaxTimePick,leftPrevYear,leftPrevMonth,leftNextYear,leftNextMonth,handleChangeRange,handleRangePick,rightPrevYear,rightPrevMonth,rightNextYear,rightNextMonth,handleClear,handleConfirm } = useSetup({
        props: defaultProps,
        renderless,
        api,
        constants: _constants,
        vm,
        parent,
        doms:[refDateRange,shortcut,minInput,minTimePicker,maxTimePicker]
      })
      return (
          
<transition name="tiny-zoom-in-top" onAfter={$emit('dodestroy')}>    
<div style={{display:state.visible?'block':'none'}} data-tag="tiny-picker-panel tiny-date-range-picker tiny-popper"  ref={refDateRange} v-ref="refDateRange" className={vc([
        m(
          gcls(['picker-panel', 'date-range-picker']),
          state.popperClass
        )
      )}>      
<div data-tag="tiny-picker-panel__body-wrapper"  className="relative">        
<Slot name="sidebar" data-tag="tiny-picker-panel__sidebar"  parent_children={props.children} slots={props.slots} className={vc([gcls('sidebar'))}></Slot>

        
<div style={{display:state.shortcuts?'block':'none'}} ref={shortcut} v-ref="shortcut" data-tag="tiny-picker-panel__sidebar"  className={vc([gcls('sidebar'))}>          

  {
    state.shortcuts.map((shortcut, key)=>(
      <button type="button" data-tag="tiny-picker-panel__shortcut"  key={key}  onClick={handleShortcutClick(shortcut)} className={vc([
              m(
                gcls('shortcut'),
                state.singleSelect &&
                  shortcut.type === state.shortcutType &&
                  shortcut.text === state.shortcutText &&
                  gcls('shortcut-selected')
              )
            )}>            
{shortcut.text}

          </button>
    ))
  }
  

        </div>

        
<div data-tag="tiny-picker-panel__body">          
<div style={{display:state.showTime?'block':'none'}} data-tag="tiny-date-range-picker__time-header"  className={vc([gcls('time-header'))}>            
<span data-tag="tiny-date-range-picker__editors-wrap"  className={vc([gcls(['editors-wrap', 'is-left']))}>              
<span data-tag="tiny-date-range-picker__time-picker-wrap"  className={vc([gcls(['time-picker-wrap', 'time-picker-wrap-left']))}>                
<tinyInput size="small" disabled={state.rangeState.selecting} ref={minInput} v-ref="minInput" placeholder={t('ui.datepicker.startDate')} data-tag="tiny-date-range-picker__editor" custom-class={gcls('editor')} modelValue={state.minVisibleDate} onUpdate:modelValue={(val) => handleDateInput(val, 'min')} onChange={(val) => handleDateChange(val, 'min')}></tinyInput>

              </span>

              
<span data-tag="tiny-date-range-picker__time-picker-wrap" clickoutside  className={vc([gcls('time-picker-wrap'))}>                
<tinyInput size="small" data-tag="tiny-date-range-picker__editor" custom-class={gcls('editor')} disabled={state.rangeState.selecting} placeholder={t('ui.datepicker.startTime')} modelValue={state.minVisibleTime} onFocus={state.minTimePickerVisible = true} onUpdate:modelValue={(val) => handleTimeInput(val, 'min')} onChange={(val) => handleTimeChange(val, 'min')}></tinyInput>

                
<timePicker ref={minTimePicker} v-ref="minTimePicker" step={step} time-arrow-control={state.arrowControl} show={state.minTimePickerVisible} value={state.minDate} onPick={handleMinTimePick}>                </timePicker>

              </span>

            </span>

            
<span data-tag="tiny-icon-arrow-right"></span>

            
<span data-tag="tiny-date-range-picker__editors-wrap is-right"  className={vc([gcls(['editors-wrap', 'is-right']))}>              
<span data-tag="tiny-date-range-picker__time-picker-wrap"  className={vc([gcls(['time-picker-wrap', 'time-picker-wrap-left']))}>                
<tinyInput size="small" data-tag="tiny-date-range-picker__editor" custom-class={gcls('editor')} disabled={state.rangeState.selecting} placeholder={t('ui.datepicker.endDate')} modelValue={state.maxVisibleDate} readonly={!state.minDate} onUpdate:modelValue={(val) => handleDateInput(val, 'max')} onChange={(val) => handleDateChange(val, 'max')}></tinyInput>

              </span>

              
<span data-tag="tiny-date-range-picker__time-picker-wrap" clickoutside  className={vc([gcls('time-picker-wrap'))}>                
<tinyInput size="small" data-tag="tiny-date-range-picker__editor" custom-class={gcls('editor')} disabled={state.rangeState.selecting} placeholder={t('ui.datepicker.endTime')} modelValue={state.maxVisibleTime} readonly={!state.minDate} onFocus={state.minDate && (state.maxTimePickerVisible = true)} onUpdate:modelValue={(val) => handleTimeInput(val, 'max')} onChange={(val) => handleTimeChange(val, 'max')}></tinyInput>

                
<timePicker ref={maxTimePicker} v-ref="maxTimePicker" step={step} time-arrow-control={state.arrowControl} show={state.maxTimePickerVisible} value={state.maxDate} onPick={handleMaxTimePick}>                </timePicker>

              </span>

            </span>

          </div>

          
<div data-tag="tiny-picker-panel__content tiny-date-range-picker__content is-left"  className={vc([gcls(['content', 'is-left']))}>            
<div data-tag="tiny-date-range-picker__header"  className={vc([gcls('header'))}>              
<button type="button" onClick={leftPrevYear} data-tag="tiny-picker-panel__icon-btn tiny-icon-d-arrow-left"  className={vc([gcls(['icon-btn', 'arrow-left']))}>                
<iconDouble ></iconDouble>

              </button>

              
<button type="button" onClick={leftPrevMonth} data-tag="tiny-picker-panel__icon-btn tiny-icon-arrow-left"  className={vc([gcls(['icon-btn', 'arrow-left']))}>                
<iconChevron ></iconChevron>

              </button>

              
<button type="button" onClick={leftNextYear} style={{display:state.unlinkPanels?'block':'none'}} disabled={!state.enableYearArrow}  data-tag="tiny-picker-panel__icon-btn tiny-icon-d-arrow-right" className={vc({ 'is-disabled': !state.enableYearArrow })}>                
<iconDouble ></iconDouble>

              </button>

              
<button type="button" onClick={leftNextMonth} style={{display:state.unlinkPanels?'block':'none'}} disabled={!state.enableMonthArrow}  data-tag="tiny-picker-panel__icon-btn tiny-icon-arrow-right" className={vc({ 'is-disabled': !state.enableMonthArrow })}>                
<iconChevron ></iconChevron>

              </button>

              
<div  className="mx-12">{state.leftLabel}</div>

            </div>

            
<dateTable selection-mode="range" date={state.leftDate} default-value={state.defaultValue} min-date={state.minDate} max-date={state.maxDate} range-state={state.rangeState} disabled-date={state.disabledDate} cell-class-name={state.cellClassName} onChangerange={handleChangeRange} first-day-of-week={state.firstDayOfWeek} show-week-number={showWeekNumber} format-weeks={formatWeeks} onPick={handleRangePick}>            </dateTable>

          </div>

          
<div data-tag="tiny-picker-panel__content tiny-date-range-picker__content is-right"  className={vc([gcls(['content', 'is-right']))}>            
<div data-tag="tiny-date-range-picker__header"  className={vc([gcls('header'))}>              
<button type="button" onClick={rightPrevYear} style={{display:state.unlinkPanels?'block':'none'}} disabled={!state.enableYearArrow}  data-tag="tiny-picker-panel__icon-btn tiny-icon-d-arrow-left" className={vc([m(gcls(['icon-btn', 'arrow-left']), !state.enableYearArrow && gcls('is-disabled')))}>                
<iconDouble ></iconDouble>

              </button>

              
<button style={{display:state.unlinkPanels?'block':'none'}} data-tag="tiny-picker-panel__icon-btn tiny-icon-arrow-left" type="button" disabled={!state.enableMonthArrow}  onClick={rightPrevMonth} className={vc([m(gcls(['icon-btn', 'arrow-left']), !state.enableMonthArrow && gcls('is-disabled')))}>                
<iconChevron ></iconChevron>

              </button>

              
<button type="button" onClick={rightNextYear} data-tag="tiny-picker-panel__icon-btn tiny-icon-d-arrow-right"  className={vc([gcls(['icon-btn', 'arrow-right']))}>                
<iconDouble ></iconDouble>

              </button>

              
<button type="button" onClick={rightNextMonth} data-tag="tiny-picker-panel__icon-btn tiny-icon-arrow-right"  className={vc([gcls(['icon-btn', 'arrow-right']))}>                
<iconChevron ></iconChevron>

              </button>

              
<div >{state.rightLabel}</div>

            </div>

            
<dateTable selection-mode="range" date={state.rightDate} default-value={state.defaultValue} min-date={state.minDate} max-date={state.maxDate} range-state={state.rangeState} disabled-date={state.disabledDate} cell-class-name={state.cellClassName} onChangerange={handleChangeRange} first-day-of-week={state.firstDayOfWeek} show-week-number={showWeekNumber} format-weeks={formatWeeks} onPick={handleRangePick}>            </dateTable>

          </div>

        </div>

      </div>

      
<div data-tag="tiny-picker-panel__footer" style={{display:state.showTime?'block':'none'}}  className={vc([gcls('footer'))}>        
<tinyButton size="mini" type="text" data-tag="tiny-picker-panel__link-btn" onClick={handleClear} custom-class="text-left pl-0">          
{t('ui.datepicker.clear')}

        </tinyButton>

        
<tinyButton type="primary" size="mini" data-tag="tiny-picker-panel__link-btn" custom-class="float-right" disabled={state.btnDisabled} onClick={handleConfirm(false)}>          
{t('ui.datepicker.confirm')}

        </tinyButton>

      </div>

    </div>

  </transition>


      );
    }

// packages/vue/src/date-panel/src/mobile-first.vue
<template>
  <transition name="tiny-zoom-in-top" @after-enter="handleEnter" @after-leave="handleLeave">
    <div
      v-show="state.visible"
      data-tag="tiny-picker-panel tiny-date-picker tiny-popper"
      :class="[gcls('picker-panel'), state.popperClass]"
    >
      <div data-tag="tiny-picker-panel__body-wrapper" :class="gcls('picker-panel-body')">
        <slot name="sidebar" data-tag="tiny-picker-panel__sidebar"></slot>
        <div data-tag="tiny-picker-panel__sidebar" v-if="state.shortcuts">
          <button
            type="button"
            data-tag="tiny-picker-panel__shortcut"
            v-for="(shortcut, key) in state.shortcuts"
            :key="key"
            @click="handleShortcutClick(shortcut)"
          >
            {{ shortcut.text }}
          </button>
        </div>
        <div data-tag="tiny-picker-panel__body" :class="gcls('picker-panel-body')">
          <div v-if="state.showTime" data-tag="tiny-date-picker__time-header" :class="gcls('time-header')">
            <span data-tag="tiny-date-picker__editor-wrap" :class="gcls('editor-wrap')">
              <tiny-input
                :placeholder="t('ui.datepicker.selectDate')"
                :model-value="state.visibleDate"
                size="small"
                @update:modelValue="(val) => (state.userInputDate = val)"
                @change="handleVisibleDateChange"
              />
            </span>
            <span
              v-clickoutside="handleTimePickClose"
              data-tag="tiny-date-picker__editor-wrap"
              :class="gcls('editor-wrap')"
            >
              <tiny-input
                ref="input"
                @focus="state.timePickerVisible = true"
                :placeholder="t('ui.datepicker.selectTime')"
                :model-value="state.visibleTime"
                size="small"
                @update:modelValue="(val) => (state.userInputTime = val)"
                @change="handleVisibleTimeChange"
              />
              <time-picker
                ref="timepicker"
                :step="step"
                :time-arrow-control="state.arrowControl"
                :show="state.timePickerVisible"
                v-if="state.timePickerVisible"
                :value="state.date"
                @pick="handleTimePick"
              >
              </time-picker>
            </span>
          </div>
          <div
            data-tag="tiny-date-picker__header"
            :class="[
              gcls('header'),
              ['month', 'year', 'years', 'yearrange'].includes(state.currentView) && gcls('bordered')
            ]"
            v-show="state.currentView !== 'time'"
          >
            <button
              type="button"
              @click="cusPrevMonth"
              v-show="state.currentView === 'date'"
              :aria-label="t(`ui.datepicker.prevMonth`)"
              data-tag="tiny-picker-panel__icon-btn tiny-date-picker__prev-btn tiny-icon-arrow-left"
              :class="[gcls('icon-btn'), 'float-left']"
            >
              <icon-chevron-left></icon-chevron-left>
            </button>
            <!-- @click="showYearPicker" -->
            <span role="button" data-tag="tiny-date-picker__header-label" :class="[gcls('header-label')]">{{
              state.yearLabel
            }}</span>
            <!-- @click="showMonthPicker" -->
            <span
              v-show="state.currentView === 'date'"
              role="button"
              data-tag="tiny-date-picker__header-label"
              :class="[gcls('header-label'), { 'text-color-brand': state.currentView === 'month' }]"
              >{{ t(`ui.datepicker.month${state.month + 1}`) }}</span
            >
            <button
              type="button"
              @click="cusNextMonth"
              v-show="state.currentView === 'date'"
              :aria-label="t(`ui.datepicker.nextMonth`)"
              data-tag="tiny-picker-panel__icon-btn tiny-date-picker__next-btn tiny-icon-arrow-right"
              :class="[gcls('icon-btn'), 'float-right']"
            >
              <icon-chevron-right></icon-chevron-right>
            </button>
          </div>

          <div data-tag="tiny-picker-panel__content" :class="gcls('content')">
            <date-table
              ref="dateTable"
              v-if="state.currentView === 'date'"
              @pick="handleDatePick"
              :selection-mode="state.selectionMode"
              :first-day-of-week="state.firstDayOfWeek"
              :value="state.value"
              :default-value="state.defaultValue ? new Date(state.defaultValue) : null"
              :date="state.date"
              :cell-class-name="state.cellClassName"
              :disabled-date="state.disabledDate"
              :show-week-number="showWeekNumber"
              :format-weeks="formatWeeks"
            >
            </date-table>
            <year-table
              ref="yearTable"
              v-if="['year', 'years', 'yearrange'].includes(state.currentView)"
              :value="state.value"
              :default-value="state.defaultValue ? new Date(state.defaultValue) : null"
              :date="state.date"
              :disabled-date="state.disabledDate"
              :selection-mode="state.selectionMode"
              :start-year="state.startYear"
              @pick="handleYearPick"
            >
            </year-table>
            <month-table
              ref="monthTable"
              v-if="state.currentView === 'month'"
              @pick="handleMonthPick"
              :value="state.value"
              :default-value="state.defaultValue ? new Date(state.defaultValue) : null"
              :date="state.date"
              :disabled-date="state.disabledDate"
            >
            </month-table>
          </div>
        </div>
      </div>

      <div
        data-tag="tiny-picker-panel__timezone"
        v-if="state.isShowTz || state.timezone.isServiceTimezone"
        v-clickoutside="handleTzPickClose"
      >
        <tiny-input
          v-model="state.tz"
          :disabled="state.timezone.isServiceTimezone"
          @update:modelValue="searchTz"
          :placeholder="t('ui.datepicker.timezone')"
        >
          <template #suffix>
            <component fill="#ccc" :is="state.showpopup ? 'IconChevronDown' : 'IconChevronUp'" @click="toggleTz" />
          </template>
        </tiny-input>
        <div data-tag="tiny-picker-panel__tzlist">
          <tiny-popup v-model="state.showpopup" :overlay="false" position="up" :duration="0.2" :closeable="false">
            <div data-tag="tzlist">
              <ul>
                <li
                  data-tag="tiny-picker-panel__tzlist-li"
                  :title="tz.name"
                  v-show="!tz.visible"
                  v-for="(tz, index) in state.renderTzdata"
                  :key="index"
                  @click="selectTz(tz)"
                >
                  {{ tz.name }}
                </li>
              </ul>
            </div>
          </tiny-popup>
        </div>
      </div>

      <div data-tag="tiny-picker-panel__footer" :class="gcls('footer')" v-show="state.isShowFooter">
        <tiny-button
          size="mini"
          type="text"
          data-tag="tiny-picker-panel__link-btn"
          :class="gcls('link-btn')"
          @click="changeToNow"
          v-show="!['dates', 'years'].includes(state.selectionMode)"
        >
          {{ t('ui.datepicker.now') }}
        </tiny-button>
        <tiny-button
          type="primary"
          size="mini"
          data-tag="tiny-picker-panel__link-btn"
          :class="['float-right', gcls('link-btn')]"
          @click="confirm"
        >
          {{ t('ui.datepicker.confirm') }}
        </tiny-button>
      </div>
    </div>
  </transition>
</template>

<script>
import { renderless, api } from '@opentiny/vue-renderless/date-panel/vue'
import { setup, directive, props, defineComponent } from '@opentiny/vue-common'
import { language } from '@opentiny/vue-locale'
import Clickoutside from '@opentiny/vue-renderless/common/deps/clickoutside'
import TimePicker from '@opentiny/vue-time'
import DateTable from '@opentiny/vue-date-table'
import YearTable from '@opentiny/vue-year-table'
import MonthTable from '@opentiny/vue-month-table'
import Input from '@opentiny/vue-input'
import Button from '@opentiny/vue-button'
import {
  IconDoubleRight,
  IconDoubleLeft,
  IconChevronLeft,
  IconChevronRight,
  IconChevronDown,
  IconChevronUp
} from '@opentiny/vue-icon'
import Popup from '@opentiny/vue-popup'
import { classes } from './token'

export default defineComponent({
  directives: directive({ Clickoutside }),
  components: {
    TimePicker,
    YearTable,
    MonthTable,
    DateTable,
    TinyInput: Input,
    TinyButton: Button,
    TinyPopup: Popup,
    IconDoubleRight: IconDoubleRight(),
    IconDoubleLeft: IconDoubleLeft(),
    IconChevronLeft: IconChevronLeft(),
    IconChevronRight: IconChevronRight(),
    IconChevronDown: IconChevronDown(),
    IconChevronUp: IconChevronUp()
  },
  props: {
    ...props,
    emitter: Object,
    step: {
      type: Object,
      default() {
        return { hour: 1, minute: 1, second: 1 }
      }
    },
    showWeekNumber: {
      type: Boolean,
      default: false
    },
    formatWeeks: Function
  },
  emits: ['pick', 'select-change', 'dodestroy'],
  setup(props, context) {
    return setup({
      props,
      context,
      renderless,
      api,
      classes,
      extendOptions: { language }
    })
  }
})
</script>
