// packages/vue/src/rich-text-editor/src/code-highlight.vue
<script lang="jsx">
import { NodeViewContent, nodeViewProps, NodeViewWrapper } from '@tiptap/vue'
import { defineComponent } from '@opentiny/vue-common'

export default defineComponent({
  name: 'CodeHighlight',
  components: {
    NodeViewWrapper,
    NodeViewContent
  },
  props: nodeViewProps,
  data() {
    return {
      languages: this.extension.options.lowlight.listLanguages()
    }
  },
  computed: {
    selectedLanguage: {
      get() {
        return this.node.attrs.language
      },
      set(language) {
        this.updateAttributes({ language })
      }
    }
  },
  render() {
    return (
      <NodeViewWrapper class="code-block">
        <select contenteditable="false" v-model={this.selectedLanguage}>
          <option value="null">auto</option>
          <option disabled>—</option>
          {this.languages.map((item, index) => (
            <option value={item} key={index}>
              {' '}
              {item}{' '}
            </option>
          ))}
        </select>
        <pre>
          <code>
            <NodeViewContent />
          </code>
        </pre>
      </NodeViewWrapper>
    )
  }
})
</script>

// packages/react-components/rich-text-editor/src/code-highlight.jsx

    import { renderless, api } from '@opentiny/vue-renderless/rich-text-editor/vue'
    import '@opentiny/vue-theme/rich-text-editor/index.less'
    import { vc, If, Component, Slot, useSetup, useVm, $props, m } from '@opentiny/react-common'
    import {useRef} from 'react'
    export default function richText(props) {
      const {} = props
      const defaultProps = {
        ...$props,
        ...props,
        
      }
      const { ref, current: vm, parent } = useVm()
      
      const { state, } = useSetup({
        props: defaultProps,
        renderless,
        api,
        constants: _constants,
        vm,
        parent,
        doms:[]
      })
      return (
          
<NodeViewWrapper  className="code-block">    
<select contenteditable="false" value={selectedLanguage} onChange={(e)=>selectedLanguage = e.value}>      
<option value="null">auto</option>

      
<option disabled>—</option>

      

  {
    languages.map((item, index)=>(
      <option  value={item} key={index}>{item}</option>
    ))
  }
  

    </select>

    
<pre ><code ><NodeViewContent ></NodeViewContent></code></pre>

  </NodeViewWrapper>


      );
    }
