// packages/vue/src/filter/src/tag-group.vue
<template>
  <div data-tag="tiny-filter-tag-group overflow-hidden" class="clear-both">
    <div
      data-tag="tag-group-label"
      class="h-5 text-sm leading-5 overflow-hidden text-ellipsis whitespace-nowrap"
      v-if="label"
    >
      {{ label }}
    </div>
    <div data-tag="tag-group-tags" class="text-left -mr-3 overflow-hidden clear-both">
      <div
        v-show="type === 'tag' && multiple"
        :class="['h-9 mt-3 float-left relative']"
        :style="{ width: state.tagWidth }"
      >
        <span
          :class="[
            'h-full block p-2 text-center rounded-sm truncate cursor-pointer border-0.5 mr-3',
            state.selected.length === 0
              ? 'border-current text-color-brand bg-color-info-primary-subtler'
              : 'border-transparent bg-color-bg-2'
          ]"
          @click.stop="selectOptionAll"
          >{{ t('ui.base.all') }}</span
        >
      </div>
      <div
        v-for="(item, index) in data"
        :key="index"
        :class="['h-9 mt-3 float-left relative']"
        :style="{ width: state.tagWidth }"
      >
        <IconSubScript
          v-if="state.selected.indexOf(item.value) !== -1 && multiple"
          class="absolute right-3 w-4 h-4 fill-color-icon-focus"
        ></IconSubScript>
        <span
          :class="[
            'h-full block p-2 text-center rounded-sm truncate cursor-pointer border-0.5 mr-3',
            state.selected.indexOf(item.value) !== -1
              ? 'border-current text-color-brand bg-color-info-primary-subtler'
              : 'border-transparent bg-color-bg-2'
          ]"
          :title="item.label"
          @click.stop="selectOption(item.value)"
          >{{ item.label }}</span
        >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { renderless, api } from '@opentiny/vue-renderless/filter/tag-group'
import { setup, $props, defineComponent } from '@opentiny/vue-common'
import { IconSubScript } from '@opentiny/vue-icon'

export default defineComponent({
  emits: ['click'],
  components: { IconSubScript: IconSubScript() },
  model: {
    prop: 'modelValue',
    event: 'update:modelValue'
  },
  props: {
    ...$props,
    modelValue: [String, Number, Array],
    data: Array,
    type: String,
    multiple: Boolean,
    columnNum: Number,
    label: String
  },
  setup(props: any, context: any) {
    return setup({ props, context, renderless, api, mono: true })
  }
})
</script>

// packages/react-components/filter/src/tag-group.jsx

    import { renderless, api } from '@opentiny/vue-renderless/filter/vue'
    import '@opentiny/vue-theme/filter/index.less'
    import { vc, If, Component, Slot, useSetup, useVm, $props, m } from '@opentiny/react-common'
    import {useRef} from 'react'
    export default function filter(props) {
      const {modelValue,data,type,multiple,columnNum,label} = props
      const defaultProps = {
        ...$props,
        ...props,
        modelValue,data,type,multiple,columnNum,label
      }
      const { ref, current: vm, parent } = useVm()
      
      const { state,selectOptionAll,selectOption } = useSetup({
        props: defaultProps,
        renderless,
        api,
        constants: _constants,
        vm,
        parent,
        doms:[]
      })
      return (
          
<div data-tag="tiny-filter-tag-group overflow-hidden"  className="clear-both">    
<div data-tag="tag-group-label"  style={{display:label?'block':'none'}} className="h-5 text-sm leading-5 overflow-hidden text-ellipsis whitespace-nowrap">      
{label}

    </div>

    
<div data-tag="tag-group-tags"  className="text-left -mr-3 overflow-hidden clear-both">      
<div style={{display:type === 'tag' && multiple?'block':'none'}}  style={{ width: state.tagWidth }} className={vc(['h-9 mt-3 float-left relative'])}>        
<span  onClick={selectOptionAll} className={vc([
            'h-full block p-2 text-center rounded-sm truncate cursor-pointer border-0.5 mr-3',
            state.selected.length === 0
              ? 'border-current text-color-brand bg-color-info-primary-subtler'
              : 'border-transparent bg-color-bg-2'
          ])}>{t('ui.base.all')}</span>

      </div>

      

  {
    data.map((item, index)=>(
      <div  key={index}  style={{ width: state.tagWidth }} className={vc(['h-9 mt-3 float-left relative'])}>        
<IconSubScript style={{display:state.selected.indexOf(item.value) !== -1 && multiple?'block':'none'}}  className="absolute right-3 w-4 h-4 fill-color-icon-focus"></IconSubScript>

        
<span  title={item.label} onClick={selectOption(item.value)} className={vc([
            'h-full block p-2 text-center rounded-sm truncate cursor-pointer border-0.5 mr-3',
            state.selected.indexOf(item.value) !== -1
              ? 'border-current text-color-brand bg-color-info-primary-subtler'
              : 'border-transparent bg-color-bg-2'
          ])}>{item.label}</span>

      </div>
    ))
  }
  

    </div>

  </div>


      );
    }
