// examples/sites/demos/pc/app/button/autofocus.vue
<template>
  <div>
    <tiny-button>默认按钮</tiny-button>
    <tiny-button autofocus>默认聚焦</tiny-button>
  </div>
</template>

<script>
import { Button } from '@opentiny/vue'

export default {
  components: {
    TinyButton: Button
  }
}
</script>

<style scoped>
.tiny-button {
  margin-bottom: 10px;
  margin-left: 0;
  margin-right: 24px;
}
</style>

// examples/react-site/demos/app/button/autofocus.jsx
import { Button as TinyButton } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(
      <div>
        <TinyButton>默认按钮</TinyButton>
        <TinyButton autofocus>默认聚焦</TinyButton>
      </div>
    );
  }
}

export default CustomElement;
