// examples/docs/resources/mobile-first/app/button/click.vue
<template>
  <tiny-button @click="click">
    默认按钮
  </tiny-button>
</template>

<script>
import { Button, Modal } from '@opentiny/vue'

export default {
  components: {
    TinyButton: Button
  },
  methods: {
    click() {
      Modal.message('click')
    }
  }
}
</script>

<style scoped>
button {
  margin: 0 16px 16px 0;
}
</style>

// examples/react-site/demos/app/button/click.jsx
import { Button as TinyButton, Modal as TinyModal } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

function App() {
  const click = () => {
    TinyModal.message({ message: 'click', status: 'info' });
  };

  return <TinyButton onClick={click}>默认按钮</TinyButton>;
}

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(<App />);
  }
}

export default CustomElement;
