// examples/docs/resources/pc/demo/button/dynamic-disabled.vue
<template>
  <tiny-layout>
    <tiny-row>
      <tiny-button @click="disabled = !disabled">
        {{ disabled ? '点击启用按钮' : '点击禁用按钮' }}
      </tiny-button>
    </tiny-row>
    <tiny-row>
      <tiny-button :icon="IconSearch" type="text" size="mini" :disabled="disabled"></tiny-button>
      <tiny-button :disabled="disabled">默认按钮</tiny-button>
      <tiny-button type="primary" :disabled="disabled">主要按钮</tiny-button>
      <tiny-button type="success" :disabled="disabled">成功按钮</tiny-button>
      <tiny-button type="info" :disabled="disabled">信息按钮</tiny-button>
      <tiny-button type="warning" :disabled="disabled">警告按钮</tiny-button>
      <tiny-button type="danger" :disabled="disabled">危险按钮</tiny-button>
    </tiny-row>

    <tiny-row>
      <tiny-button :disabled="disabled" plain>默认按钮</tiny-button>
      <tiny-button type="primary" :disabled="disabled" plain>主要按钮</tiny-button>
      <tiny-button type="success" :disabled="disabled" plain>成功按钮</tiny-button>
      <tiny-button type="info" :disabled="disabled" plain>信息按钮</tiny-button>
      <tiny-button type="warning" :disabled="disabled" plain>警告按钮</tiny-button>
      <tiny-button type="danger" :disabled="disabled" plain>危险按钮</tiny-button>
    </tiny-row>
  </tiny-layout>
</template>

<script lang="jsx">
import { Button, Layout, Row } from '@opentiny/vue'
import { IconSearch } from '@opentiny/vue-icon'

export default {
  components: {
    TinyButton: Button,
    TinyLayout: Layout,
    TinyRow: Row
  },
  data() {
    return {
      disabled: false,
      IconSearch: IconSearch()
    }
  }
}
</script>

<style scoped>
.tiny-row {
  margin-bottom: 20px;
}
</style>

// examples/react-site/demos/app/button/dynamic-disabled.jsx
import { Button as TinyButton, Layout as TinyLayout, Row as TinyRow, Switch as TinySwitch } from '@opentiny/react';
import { IconSearch } from '@opentiny/react-icon';
import { useState } from 'react';
import ReactDOM from 'react-dom/client';

const scopeId = 'scope-' + Math.random().toString(36).substr(2, 9);

function App() {
  const [disabled, setDisabled] = useState(false);

  return (
    <div>
      <style>
        {`
          [data-v="${scopeId}"] .tiny-row {
            margin-bottom: 20px;
          }
          [data-v="${scopeId}"] .tiny-button {
            margin-bottom: 10px;
            margin-left: 0;
            margin-right: 8px;
          }
        `}
      </style>
      <div data-v={scopeId}>
        <TinyLayout>
          <TinyRow>
            是否禁用：<TinySwitch checked={disabled} onChange={setDisabled}></TinySwitch>
          </TinyRow>
          <TinyRow>
            <TinyButton disabled={disabled}>默认按钮</TinyButton>
            <TinyButton type="primary" disabled={disabled}>
              主要按钮
            </TinyButton>
            <TinyButton type="success" disabled={disabled}>
              成功按钮
            </TinyButton>
            <TinyButton type="info" disabled={disabled}>
              信息按钮
            </TinyButton>
            <TinyButton type="warning" disabled={disabled}>
              警告按钮
            </TinyButton>
            <TinyButton type="danger" disabled={disabled}>
              危险按钮
            </TinyButton>
          </TinyRow>
          <TinyRow>
            <TinyButton disabled={disabled} plain>
              朴素按钮
            </TinyButton>
            <TinyButton type="primary" disabled={disabled} plain>
              主要按钮
            </TinyButton>
            <TinyButton type="success" disabled={disabled} plain>
              成功按钮
            </TinyButton>
            <TinyButton type="info" disabled={disabled} plain>
              信息按钮
            </TinyButton>
            <TinyButton type="warning" disabled={disabled} plain>
              警告按钮
            </TinyButton>
            <TinyButton type="danger" disabled={disabled} plain>
              危险按钮
            </TinyButton>
          </TinyRow>
          <TinyRow>
            <TinyButton disabled={disabled} ghost>
              幽灵按钮
            </TinyButton>
            <TinyButton icon={IconSearch} disabled={disabled}>
              图标按钮
            </TinyButton>
            <TinyButton icon={IconSearch} disabled={disabled}></TinyButton>
            <TinyButton icon={IconSearch} disabled={disabled} circle></TinyButton>
          </TinyRow>
        </TinyLayout>
      </div>
    </div>
  );
}

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(<App />);
  }
}

export default CustomElement;
