// example/src/demo/pc/button/image.vue
<template>
  <tiny-button>
    <img :src="image" width="26" />
    <span>图片按钮</span>
  </tiny-button>
</template>

<script>
import { Button } from '@opentiny/vue'

export default {
  components: {
    TinyButton: Button
  },
  data() {
    return {
      image: 'static/images/button-image.png'
    }
  }
}
</script>

// examples/react-site/demos/app/button/image.jsx
import { Button as TinyButton } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

class CustomElement extends HTMLElement {
  connectedCallback() {
    const image = `${import.meta.env.BASE_URL}static/images/button-image.png`;

    ReactDOM.createRoot(this).render(
      <TinyButton>
        <img src={image} width="26" />
        <span>图片按钮</span>
      </TinyButton>
    );
  }
}

export default CustomElement;
