// examples/sites/demos/pc/app/button/reset-time.vue
<template>
  <div>
    <tiny-button>默认禁用</tiny-button>
    <tiny-button :reset-time="0">无禁用</tiny-button>
    <tiny-button :reset-time="5000">禁用 5 秒</tiny-button>
  </div>
</template>

<script>
import { Button } from '@opentiny/vue'

export default {
  components: {
    TinyButton: Button
  }
}
</script>

// examples/react-site/demos/app/button/reset-time.jsx
import { Button as TinyButton } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(
      <div>
        <TinyButton>默认禁用</TinyButton>
        <TinyButton resetTime={0}>无禁用</TinyButton>
        <TinyButton resetTime={5000}>禁用 5 秒</TinyButton>
      </div>
    );
  }
}

export default CustomElement;
