// examples/docs/resources/pc/demo/layout/order.vue
<template>
  <div class="content">
    <tiny-layout>
      <tiny-row :flex="true" :gutter="20" :order="state.order">
        <tiny-col :span="3" :no="3">
          <div class="col">3</div>
        </tiny-col>
        <tiny-col :span="3" :no="1">
          <div class="col">1</div>
        </tiny-col>
        <tiny-col :span="3" :no="2">
          <div class="col">2</div>
        </tiny-col>
        <tiny-col :span="3" :no="4">
          <div class="col">4</div>
        </tiny-col>
      </tiny-row>
      <tiny-row :flex="true" :gutter="20" justify="center">
        <tiny-button @click="toggleOrder">
          {{ state.buttonLabel }}
        </tiny-button>
      </tiny-row>
    </tiny-layout>
  </div>
</template>

<script lang="jsx">
import { Layout, Row, Col, Button } from '@opentiny/vue'

export default {
  components: {
    TinyLayout: Layout,
    TinyRow: Row,
    TinyCol: Col,
    TinyButton: Button
  },
  data() {
    return {
      state: {
        buttonLabel: '升序',
        order: 'asc'
      }
    }
  },
  methods: {
    toggleOrder() {
      if (this.state.buttonLabel === '升序') {
        this.state.buttonLabel = '降序'
        this.state.order = 'des'
      } else {
        this.state.buttonLabel = '升序'
        this.state.order = 'asc'
      }
    }
  }
}
</script>

<style scoped>
.tiny-row {
  margin-bottom: 20px;
}

.tiny-row .last-child {
  margin-bottom: 0;
}

.tiny-col .col {
  line-height: 30px;
  text-align: center;
  color: #fff;
  background: #1f9ed8;
  border-radius: 15px;
}

.tiny-col:nth-child(even) .col {
  background: #73d0fc;
}
</style>

// examples/react-site/demos/app/layout/order.jsx
import { Layout as TinyLayout, Row as TinyRow, Col as TinyCol, Button as TinyButton } from '@opentiny/react';
import ReactDOM from 'react-dom/client';
import { useState } from 'react';

const scopeId = 'scope-' + Math.random().toString(36).substr(2, 9);

function App() {
  const [state, setState] = useState({
    buttonLabel: '升序',
    order: 'asc',
  });

  const toggleOrder = () => {
    setState(prevState => ({
      ...prevState,
      buttonLabel: prevState.buttonLabel === '升序' ? '降序' : '升序',
      order: prevState.order === 'asc' ? 'des' : 'asc',
    }));
  };

  return (
    <div>
      <style>{`
      [data-v="${scopeId}"] .tiny-row {
        margin-bottom: 20px;
      }

      [data-v="${scopeId}"] .tiny-row .last-child {
        margin-bottom: 0;
      }

      [data-v="${scopeId}"] .tiny-col .col {
        line-height: 30px;
        text-align: center;
        color: #fff;
        background: #1f9ed8;
        border-radius: 15px;
      }

      [data-v="${scopeId}"] .tiny-col:nth-child(even) .col {
        background: #73d0fc;
      }
    `}</style>
      <div data-v={scopeId}>
        <TinyLayout>
          <TinyRow>
            <TinyButton onClick={toggleOrder}>{state.buttonLabel}</TinyButton>
          </TinyRow>
          <TinyRow flex={true} gutter={20} order={state.order}>
            <TinyCol span={3} no={3}>
              <div className="col">3</div>
            </TinyCol>
            <TinyCol span={3} no={1}>
              <div className="col">1</div>
            </TinyCol>
            <TinyCol span={3} no={2}>
              <div className="col">2</div>
            </TinyCol>
            <TinyCol span={3} no={4}>
              <div className="col">4</div>
            </TinyCol>
          </TinyRow>
        </TinyLayout>
      </div>
    </div>
  );
}

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(<App />);
  }
}

export default CustomElement;
