// examples/react-site/demos/app/button/click.jsx
import { Button as TinyButton, Modal as TinyModal } from '@opentiny/react';
import ReactDOM from 'react-dom/client';

function App() {
  const click = () => {
    TinyModal.message({ message: 'click', status: 'info' });
  };

  return <TinyButton onClick={click}>默认按钮</TinyButton>;
}

class CustomElement extends HTMLElement {
  connectedCallback() {
    ReactDOM.createRoot(this).render(<App />);
  }
}

export default CustomElement;

// examples/sites/demos/pc/app/button/click.vue
<template>
  <tiny-button @click="click">默认按钮</tiny-button>
</template>

<script>
import { TinyButton, TinyModal } from '@opentiny/vue'

export default {
  components: {
    TinyButton
  },
  methods: {
    click() {
      TinyModal.message({ message: 'click', status: 'info' })
    }
  }
}
</script>
