// packages/react-components/action-sheet/src/option.jsx

    import { renderless, api } from '@opentiny/vue-renderless/action-sheet/vue'
    import '@opentiny/vue-theme/action-sheet/index.less'
    import { vc, If, Component, Slot, useSetup, useVm, $props, m } from '@opentiny/react-common'
    import {useRef} from 'react'
    export default function actionSheet(props) {
      const {selected,ellipsis,multiple} = props
      const defaultProps = {
        ...$props,
        ...props,
        selected,ellipsis,multiple
      }
      const { ref, current: vm, parent } = useVm()
      
      const { state, } = useSetup({
        props: defaultProps,
        renderless,
        api,
        constants: _constants,
        vm,
        parent,
        doms:[]
      })
      return (
          
<div  onClick={$emit('click', $event)} className="flex items-start leading-5.5 py-3 cursor-pointer select-none">    
<Component style={{display:multiple?'block':'none'}} is={selected ? 'icon-checked-sur' : 'icon-check'}  className={vc(['flex-none w-4 h-4 mt-0.5 mr-2', selected ? 'fill-color-brand' : 'fill-color-icon-disabled'])}></Component>

    
<div  className={vc(['flex-auto', { 'truncate': ellipsis }, { 'text-color-brand': !multiple && selected }])}>      
<Slot  parent_children={props.children} slots={props.slots}></Slot>

    </div>

  </div>


      );
    }

// packages/vue/src/select-mobile/src/option.vue
<template>
  <div class="flex items-start leading-6 py-3 cursor-pointer select-none" @click="$emit('click', $event)">
    <component v-if="multiple" :is="selected ? 'icon-checked-sur' : 'icon-check'" :class="['flex-none mt-1 mr-2', selected ? 'fill-color-brand' : 'fill-color-icon-disabled']" custom-class="w-4.5 h-4.5" />
    <div :class="['flex-auto', { 'truncate': ellipsis }, { 'text-color-brand': !multiple && selected }]">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { IconHalfselect, IconCheckedSur, IconCheck } from '@opentiny/vue-icon'
import { defineComponent } from '@opentiny/vue-common'

export default defineComponent({
  emits: ['click'],
  components: {
    IconCheck: IconCheck(),
    IconCheckedSur: IconCheckedSur(),
    IconHalfselect: IconHalfselect()
  },
  props: ['selected', 'ellipsis', 'multiple']
})
</script>
