// examples/docs/resources/mobile-first/app/alert/type.vue
<template>
  <div>
    <tiny-alert type="info" description="type 为 info"></tiny-alert>
    <tiny-alert type="error" description="type 为 error"></tiny-alert>
    <tiny-alert type="success" description="type 为 success"></tiny-alert>
    <tiny-alert type="warning" description="type 为 warning"></tiny-alert>
  </div>
</template>

<script>
import { Alert, Button } from '@opentiny/vue'

export default {
  components: {
    TinyAlert: Alert,
    TinyButton: Button
  }
}
</script>

// examples/react-docs/demos/pc/app/alert/type.jsx
import { Alert as TinyAlert } from '@opentiny/react'

function App() {
  return (
    <div>
      <TinyAlert description="type 为默认值 success"></TinyAlert>
      <TinyAlert type="info" description="type 为 info"></TinyAlert>
      <TinyAlert type="error" description="type 为 error"></TinyAlert>
      <TinyAlert type="success" description="type 为 success"></TinyAlert>
      <TinyAlert type="warning" description="type 为 warning"></TinyAlert>
    </div>
  )
}

export default App
