// packages/input/src/tall-storage.vue
<template>
  <div class="tiny-tall-storage" @mousedown="mousedown">
    <div class="tiny-storage-list-style">
      <ul @keydown.enter="keydownEvent" class="tiny-storage-list">
        <li
          v-for="item in localstorageData"
          v-bind:key="item"
          class="tiny-storage-item"
          :class="[state.hoverValue === item ? 'item-hover' : '']"
          @click="selectItem(item)"
        >
          {{ item }}
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import { $prefix, setup } from '@opentiny/vue-common'
import {
  renderless,
  api
} from '@opentiny/vue-renderless/tall-storage/vue'
import '@opentiny/vue-theme/tall-storage/index.css'

export default {
  name: $prefix + 'TallStorage',
  inheritAttrs: false,
  props: {
    isMemoryStorage: Boolean,
    localstorageData: Array
  },
  setup(props, context) {
    return setup({ props, context, renderless, api, mono: true })
  }
}
</script>

// packages/react-components/input/src/tall-storage.jsx

    import { renderless, api } from '@opentiny/vue-renderless/input/vue'
    import '@opentiny/vue-theme/input/index.less'
    import { vc, If, Component, Slot, useSetup, useVm, $props, m } from '@opentiny/react-common'
    import {useRef} from 'react'
    export default function input(props) {
      const {isMemoryStorage,localstorageData} = props
      const defaultProps = {
        ...$props,
        ...props,
        isMemoryStorage,localstorageData
      }
      const { ref, current: vm, parent } = useVm()
      
      const { state,mousedown,keydownEvent,selectItem } = useSetup({
        props: defaultProps,
        renderless,
        api,
        constants: _constants,
        vm,
        parent,
        doms:[]
      })
      return (
          
<div  onMousedown={mousedown} className="tiny-tall-storage">    
<div  className="tiny-storage-list-style">      
<ul onKeydown={keydownEvent}  className="tiny-storage-list">        

  {
    localstorageData.map(item=>(
      <li  key={item}   onClick={selectItem(item)} className={vc([state.hoverValue === item ? 'item-hover' : ''],'tiny-storage-item')}>          
{item}

        </li>
    ))
  }
  

      </ul>

    </div>

  </div>


      );
    }
